params ["_logic"];
if (!hasInterface) exitWith {};
private _data = _logic getVariable ["TAE_requisitionData", []];
if (_data isEqualTo []) exitWith {};
_data params ["_terminal", "_pad", "_authorized", "_radius"];
private _near = (nearestObjects [_pad, ["Air"], _radius, true]) select {alive _x && {abs ((getPosASL _x # 2) - (getPosASL _pad # 2)) < 15}};
if (count _near != 1) exitWith {systemChat "Exactly one intact aircraft must be on the pad.";};
private _vehicle = _near # 0;
if !(_vehicle getVariable ["ace_cargo_hasCargo", getNumber (configOf _vehicle >> "ace_cargo_hasCargo") == 1]) exitWith {systemChat "This aircraft does not support ACE cargo.";};
private _display = findDisplay 46 createDisplay "RscDisplayEmpty";
_display setVariable ["TAE_logic", _logic];
_display setVariable ["TAE_vehicle", _vehicle];
private _panel = _display ctrlCreate ["RscText", -1];
_panel ctrlSetPosition [0.18, 0.10, 0.64, 0.78];
_panel ctrlSetBackgroundColor [0.08, 0.08, 0.08, 1];
_panel ctrlCommit 0;
private _title = _display ctrlCreate ["RscText", -1];
_title ctrlSetPosition [0.20, 0.12, 0.60, 0.05];
_title ctrlSetText "Resupply Crates";
_title ctrlCommit 0;
private _loaded = _vehicle getVariable ["ace_cargo_loaded", []];
private _classes = call TAE_fnc_getResupplyCrateClasses;
private _available = [_vehicle] call ace_cargo_fnc_getCargoSpaceLeft;
private _edits = [];
{
    private _class = _x;
    private _count = {_class == (if (_x isEqualType "") then {_x} else {typeOf _x})} count _loaded;
    _available = _available + _count * (getNumber (configFile >> "CfgVehicles" >> _class >> "ace_cargo_size"));
    private _label = _display ctrlCreate ["RscText", -1];
    _label ctrlSetPosition [0.20, 0.24 + _forEachIndex * 0.065, 0.47, 0.055];
    _label ctrlSetText getText (configFile >> "CfgVehicles" >> _class >> "displayName");
    _label ctrlCommit 0;
    private _edit = _display ctrlCreate ["RscEdit", -1];
    _edit ctrlSetPosition [0.69, 0.24 + _forEachIndex * 0.065, 0.09, 0.055];
    _edit ctrlSetText str _count;
    _edit ctrlCommit 0;
    _edits pushBack _edit;
} forEach _classes;
_display setVariable ["TAE_edits", _edits];
private _capacity = _display ctrlCreate ["RscText", -1];
_capacity ctrlSetPosition [0.20, 0.18, 0.60, 0.05];
_capacity ctrlSetText format ["Space available for these crates: %1", _available];
_capacity ctrlCommit 0;
private _warning = _display ctrlCreate ["RscText", -1];
_warning ctrlSetPosition [0.20, 0.70, 0.60, 0.05];
_warning ctrlSetText "Apply replaces these crates with fresh supplies. Other cargo stays.";
_warning ctrlCommit 0;
private _button = _display ctrlCreate ["RscButton", -1];
_button ctrlSetPosition [0.52, 0.79, 0.26, 0.06];
_button ctrlSetText "Apply Crate Loadout";
_button ctrlCommit 0;
_button ctrlAddEventHandler ["ButtonClick", {
    private _display = ctrlParent (_this # 0);
    private _counts = [];
    private _valid = true;
    {
        private _text = ctrlText _x;
        if (_text == "" || {(toArray _text) findIf {_x < 48 || {_x > 57}} != -1}) then {_valid = false;};
        _counts pushBack parseNumber _text;
    } forEach (_display getVariable ["TAE_edits", []]);
    if (!_valid) exitWith {systemChat "Enter whole, non-negative crate counts.";};
    ["TAE_aircraftRequest", [_display getVariable "TAE_logic", player, "crates", [_display getVariable "TAE_vehicle", _counts]]] call CBA_fnc_serverEvent;
    _display closeDisplay 1;
}];
private _cancel = _display ctrlCreate ["RscButton", -1];
_cancel ctrlSetPosition [0.20, 0.79, 0.26, 0.06];
_cancel ctrlSetText "Cancel";
_cancel ctrlCommit 0;
_cancel ctrlAddEventHandler ["ButtonClick", {(ctrlParent (_this # 0)) closeDisplay 2;}];
